### PR TITLE
V0.0.8

### PR DESCRIPTION
**Pull request by sullof**
This pull request adds the option `short` to obtain the result requested by @NearAutomata in https://github.com/sullof/inquirer-command-prompt/pull/7 without breaking the other behaviors of the plugin.

### CODE REVIEW

**Comment by NearAutomata** [comment]
Alright I was just able to test your proposed changes and found them to be buggy. For usual autocompletion of commands and their options it works, but customized items such as options values (without preceeding hyphen) cause some issues as they are not entirely matched by the regular expression. The result is the following:

screen shot 2018-05-13 at 12 50 20

In the picture you can see that your changes can't handle it when I'm trying to auto complete the `optA` and `optC` option values for the flags. The term "can't handle" refers to the fact that the entire line is written on-screen rather than just the supplied option values. And yes my `autoCompletion` function returns an array with the full command line such as the following example:
```
["isb -b --aab-long -a optA", "isb -b --aab-long -a optB", "isb -b --aab-long -a optC"]
```
As you may have noticed my initial PR should have removed the prefix `isb -b --aab-long -a ` from all of those array items when writing the list of available commands.

Furthermore I don't particularly understand your `short` function since it is so cryptic. Can you elaborate in which test cases my suggestion of just writing
```typescript
console.log(CommandPrompt.formatList(
    ac.matches.map(function (value) { return value.split(" ").slice(-1).join(); })))
```
is causing issues? I expected that it would only change the text that is written on-screen, not the internal representation of the auto complete suggestions.

**Comment by sullof** [comment]
Thanks. 

The problem with your solution is that breaks some cases. For example, if you execute https://github.com/NearAutomata/inquirer-command-prompt/blob/blacklight-fork/examples/autocompletion.js in your branch, you will see that last case (`show [friend id]`) fails.

Since your request makes sense in many cases, I was trying to find a general solution that works using an optional parameter, without breaking other cases. It is definitely buggy. I will try to fix it.

**Comment by NearAutomata** [comment]
Ah didn't see the case where something would have a more sophisticated name that has a space etc, fair enough. I didn't expect an autocompletion to return "show [friend id]" as that would require the user to delete the bracketed part, wouldn't it?

Such a case where your proposed code fails is described in my first comment in this thread:
```
["isb -b --aab-long -a optA", "isb -b --aab-long -a optB", "isb -b --aab-long -a optC"]
```
For each step in the completion of `isb -b --aab-long -a optX` I had no issues since every single chunk after the command starts with a hyphen until the very end. Once I had typed `isb -b --aab-long -a opt` into the console and pressed tab my function would return the above array and your `short` fails to shorten the prefix all have in common. I'd expect to see `optA`, `optB` and `optC` being suggested, but like in the screenshot it suggests `isb -b --aab-long -a optA`, `isb -b --aab-long -a optB` and `isb -b --aab-long -a optC`.

**Comment by sullof** [comment]
Thanks.

**Comment by sullof** [comment]
I fixed the issue. There was a mistake in a regular expression. I also added your specific example in `examples/autocompletion.js`. Let me know.

**Comment by sullof** [comment]
About the motivations. The `short` method removes from the suggestion the part of the command that has been already typed. Requiring an explicit option, it keeps compatibility with previous use cases.

**Comment by NearAutomata** [comment]
I can confirm that it works now as wished with the optional `short` option.

**Comment by sullof** [comment]
Good. I will merge it and publish on npm.

**Pull request merged**
